version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./app:/app
    environment:
      - FOOD_HOST=http://167.71.221.107:5004/food/base64
      - HOST=http://167.71.221.107:5004
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
